title:              Zhiyu He
email:              zhiyhe@ethz.ch
description:        Homepage of Zhiyu He
author:             Zhiyu He
baseurl:            ""
url:                "https://zyhe.github.io"

# Social Profiles
twitter_username:   
github_username: zyhe   
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-C0YTJSLE5C # out your google-analytics code

exclude:
  - vendor

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-reading-time
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# # Navigation Configuration
# navigation:
#   - name: "Home"
#     link: "/"
#   - name: "Publication"
#     link: "/publications.html"
#   - name: "Teaching"
#     link: "/teaching.html"
#   - name: "Posts"
#     link: "/posts/"